baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/blog/:slug/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe= true